import activityIcon from "@iconify-icons/lucide/activity";
import alertCircleIcon from "@iconify-icons/lucide/alert-circle";
import arrowLeftIcon from "@iconify-icons/lucide/arrow-left";
import arrowRightIcon from "@iconify-icons/lucide/arrow-right";
import arrowUpIcon from "@iconify-icons/lucide/arrow-up";
import boxIcon from "@iconify-icons/lucide/box";
import calendarDaysIcon from "@iconify-icons/lucide/calendar-days";
import calendarRangeIcon from "@iconify-icons/lucide/calendar-range";
import checkIcon from "@iconify-icons/lucide/check";
import chevronLeftIcon from "@iconify-icons/lucide/chevron-left";
import chevronRightIcon from "@iconify-icons/lucide/chevron-right";
import clockIcon from "@iconify-icons/lucide/clock";
import cloudIcon from "@iconify-icons/lucide/cloud";
import cloudOffIcon from "@iconify-icons/lucide/cloud-off";
import copyIcon from "@iconify-icons/lucide/copy";
import downloadIcon from "@iconify-icons/lucide/download";
import eraserIcon from "@iconify-icons/lucide/eraser";
import externalLinkIcon from "@iconify-icons/lucide/external-link";
import fileIcon from "@iconify-icons/lucide/file";
import fileTextIcon from "@iconify-icons/lucide/file-text";
import flagIcon from "@iconify-icons/lucide/flag";
import folderIcon from "@iconify-icons/lucide/folder";
import folderOpenIcon from "@iconify-icons/lucide/folder-open";
import folderPlusIcon from "@iconify-icons/lucide/folder-plus";
import globeIcon from "@iconify-icons/lucide/globe";
import grid2X2Icon from "@iconify-icons/lucide/grid-2x2";
import homeIcon from "@iconify-icons/lucide/home";
import imageIcon from "@iconify-icons/lucide/image";
import infoIcon from "@iconify-icons/lucide/info";
import keyRoundIcon from "@iconify-icons/lucide/key-round";
import layers2Icon from "@iconify-icons/lucide/layers-2";
import layoutGridIcon from "@iconify-icons/lucide/layout-grid";
import listIcon from "@iconify-icons/lucide/list";
import loader2Icon from "@iconify-icons/lucide/loader-2";
import lockIcon from "@iconify-icons/lucide/lock";
import logOutIcon from "@iconify-icons/lucide/log-out";
import maximize2Icon from "@iconify-icons/lucide/maximize-2";
import minimize2Icon from "@iconify-icons/lucide/minimize-2";
import minusIcon from "@iconify-icons/lucide/minus";
import moreHorizontalIcon from "@iconify-icons/lucide/more-horizontal";
import moveHorizontalIcon from "@iconify-icons/lucide/move-horizontal";
import paletteIcon from "@iconify-icons/lucide/palette";
import pauseIcon from "@iconify-icons/lucide/pause";
import pencilIcon from "@iconify-icons/lucide/pencil";
import playIcon from "@iconify-icons/lucide/play";
import plusIcon from "@iconify-icons/lucide/plus";
import rotateCcwIcon from "@iconify-icons/lucide/rotate-ccw";
import refreshCwIcon from "@iconify-icons/lucide/refresh-cw";
import rotateCwIcon from "@iconify-icons/lucide/rotate-cw";
import saveIcon from "@iconify-icons/lucide/save";
import searchIcon from "@iconify-icons/lucide/search";
import settingsIcon from "@iconify-icons/lucide/settings";
import share2Icon from "@iconify-icons/lucide/share-2";
import shieldIcon from "@iconify-icons/lucide/shield";
import sparklesIcon from "@iconify-icons/lucide/sparkles";
import terminalIcon from "@iconify-icons/lucide/terminal";
import timerIcon from "@iconify-icons/lucide/timer";
import trash2Icon from "@iconify-icons/lucide/trash-2";
import typeIcon from "@iconify-icons/lucide/type";
import unlockIcon from "@iconify-icons/lucide/unlock";
import uploadIcon from "@iconify-icons/lucide/upload";
import volume2Icon from "@iconify-icons/lucide/volume-2";
import volumeXIcon from "@iconify-icons/lucide/volume-x";
import wallpaperIcon from "@iconify-icons/lucide/wallpaper";
import xIcon from "@iconify-icons/lucide/x";
import zoomInIcon from "@iconify-icons/lucide/zoom-in";
import zoomOutIcon from "@iconify-icons/lucide/zoom-out";

import { createIcon } from "./createIcon";

const rotateCwSquareIcon = {
  width: 24,
  height: 24,
  body: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M12 5H6a2 2 0 0 0-2 2v3"/><path d="m9 8 3-3-3-3"/><path d="M4 14v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"/></g>',
};

export const Activity = createIcon(activityIcon, "Activity");
export const AlertCircle = createIcon(alertCircleIcon, "AlertCircle");
export const ArrowLeft = createIcon(arrowLeftIcon, "ArrowLeft");
export const ArrowRight = createIcon(arrowRightIcon, "ArrowRight");
export const ArrowUp = createIcon(arrowUpIcon, "ArrowUp");
export const Box = createIcon(boxIcon, "Box");
export const CalendarDays = createIcon(calendarDaysIcon, "CalendarDays");
export const CalendarRange = createIcon(calendarRangeIcon, "CalendarRange");
export const Check = createIcon(checkIcon, "Check");
export const ChevronLeft = createIcon(chevronLeftIcon, "ChevronLeft");
export const ChevronRight = createIcon(chevronRightIcon, "ChevronRight");
export const Clock = createIcon(clockIcon, "Clock");
export const Cloud = createIcon(cloudIcon, "Cloud");
export const CloudOff = createIcon(cloudOffIcon, "CloudOff");
export const Copy = createIcon(copyIcon, "Copy");
export const Download = createIcon(downloadIcon, "Download");
export const Eraser = createIcon(eraserIcon, "Eraser");
export const ExternalLink = createIcon(externalLinkIcon, "ExternalLink");
export const File = createIcon(fileIcon, "File");
export const FileText = createIcon(fileTextIcon, "FileText");
export const Flag = createIcon(flagIcon, "Flag");
export const Folder = createIcon(folderIcon, "Folder");
export const FolderOpen = createIcon(folderOpenIcon, "FolderOpen");
export const FolderPlus = createIcon(folderPlusIcon, "FolderPlus");
export const Globe = createIcon(globeIcon, "Globe");
export const Grid2X2 = createIcon(grid2X2Icon, "Grid2X2");
export const Home = createIcon(homeIcon, "Home");
export const Image = createIcon(imageIcon, "Image");
export const Info = createIcon(infoIcon, "Info");
export const KeyRound = createIcon(keyRoundIcon, "KeyRound");
export const Layers2 = createIcon(layers2Icon, "Layers2");
export const LayoutGrid = createIcon(layoutGridIcon, "LayoutGrid");
export const List = createIcon(listIcon, "List");
export const Loader2 = createIcon(loader2Icon, "Loader2");
export const Lock = createIcon(lockIcon, "Lock");
export const LogOut = createIcon(logOutIcon, "LogOut");
export const Maximize2 = createIcon(maximize2Icon, "Maximize2");
export const Minimize2 = createIcon(minimize2Icon, "Minimize2");
export const Minus = createIcon(minusIcon, "Minus");
export const MoreHorizontal = createIcon(moreHorizontalIcon, "MoreHorizontal");
export const MoveHorizontal = createIcon(moveHorizontalIcon, "MoveHorizontal");
export const Palette = createIcon(paletteIcon, "Palette");
export const Pause = createIcon(pauseIcon, "Pause");
export const Pencil = createIcon(pencilIcon, "Pencil");
export const Play = createIcon(playIcon, "Play");
export const Plus = createIcon(plusIcon, "Plus");
export const RotateCcw = createIcon(rotateCcwIcon, "RotateCcw");
export const RefreshCw = createIcon(refreshCwIcon, "RefreshCw");
export const RotateCw = createIcon(rotateCwIcon, "RotateCw");
export const RotateCwSquare = createIcon(rotateCwSquareIcon, "RotateCwSquare");
export const Save = createIcon(saveIcon, "Save");
export const Search = createIcon(searchIcon, "Search");
export const Settings = createIcon(settingsIcon, "Settings");
export const Share2 = createIcon(share2Icon, "Share2");
export const Shield = createIcon(shieldIcon, "Shield");
export const Sparkles = createIcon(sparklesIcon, "Sparkles");
export const Terminal = createIcon(terminalIcon, "Terminal");
export const TerminalIcon = Terminal;
export const Timer = createIcon(timerIcon, "Timer");
export const Trash2 = createIcon(trash2Icon, "Trash2");
export const Type = createIcon(typeIcon, "Type");
export const Unlock = createIcon(unlockIcon, "Unlock");
export const Upload = createIcon(uploadIcon, "Upload");
export const Volume2 = createIcon(volume2Icon, "Volume2");
export const VolumeX = createIcon(volumeXIcon, "VolumeX");
export const Wallpaper = createIcon(wallpaperIcon, "Wallpaper");
export const X = createIcon(xIcon, "X");
export const ZoomIn = createIcon(zoomInIcon, "ZoomIn");
export const ZoomOut = createIcon(zoomOutIcon, "ZoomOut");
