export const ANIMAL_KINDS = [
  "ant",
  "bear",
  "bison",
  "buffalo",
  "cat-1",
  "cat-2",
  "cat-3",
  "cat-4",
  "cat-5",
  "chicken",
  "chococat",
  "cow",
  "crocodile",
  "dog-1",
  "dog-2",
  "dog-3",
  "dog-4",
  "dog-5",
  "doraemon",
  "duck",
  "eagle",
  "elephant",
  "fox",
  "giraffe",
  "gorilla",
  "hedgehog",
  "hello-kitty",
  "hippo",
  "horse",
  "keroppi",
  "koala",
  "leopard",
  "lion",
  "monkey",
  "moose",
  "mouse",
  "otter",
  "owl",
  "panda",
  "penguin",
  "pig",
  "pikachu",
  "raccoon",
  "sheep",
  "sloth",
  "snake",
  "squirrel",
  "tiger",
  "wolf",
  "zebra",
] as const;

export const SOFT_ANIMAL_KINDS = [
  "soft-animal-01",
  "soft-animal-02",
  "soft-animal-03",
  "soft-animal-04",
  "soft-animal-05",
  "soft-animal-06",
  "soft-animal-07",
  "soft-animal-08",
  "soft-animal-09",
  "soft-animal-10",
  "soft-animal-11",
  "soft-animal-12",
  "soft-animal-13",
  "soft-animal-14",
  "soft-animal-15",
  "soft-animal-16",
  "soft-animal-17",
  "soft-animal-18",
  "soft-animal-19",
  "soft-animal-20",
  "soft-animal-21",
  "soft-animal-22",
  "soft-animal-23",
  "soft-animal-24",
  "soft-animal-25",
  "soft-animal-26",
  "soft-animal-27",
  "soft-animal-28",
  "soft-animal-29",
  "soft-animal-30",
  "soft-animal-31",
  "soft-animal-32",
  "soft-animal-33",
  "soft-animal-34",
  "soft-animal-35",
  "soft-animal-36",
] as const;

export const STICKER_SETS = [
  {
    featuredKind: "giraffe",
    family: "animal",
    hueStart: 24,
    kinds: ANIMAL_KINDS,
    label: "Animals",
    scene: "animals",
  },
  {
    featuredKind: "soft-animal-01",
    family: "soft-animal",
    hueStart: 156,
    kinds: SOFT_ANIMAL_KINDS,
    label: "Soft Animals",
    scene: "soft-animals",
  },
] as const;
