/**
 * Where the Blog app pulls live content from at runtime.
 *
 * Posts live as `blog/<slug>.md` in the GitHub repo and are fetched directly
 * from raw.githubusercontent.com so new posts appear without redeploying the
 * app. `blog/index.json` (generated by CI) drives the index list.
 *
 * To move content behind a CDN or same-origin proxy later, only `BLOG_RAW_BASE`
 * needs to change (e.g. `https://cdn.jsdelivr.net/gh/daopk/daopk.me@main/blog`
 * or `/blog`).
 */
export const BLOG_REPO_OWNER = "daopk";
export const BLOG_REPO_NAME = "daopk.me";
export const BLOG_REPO_BRANCH = "main";
export const BLOG_CONTENT_DIR = "blog";
export const BLOG_INDEX_FILENAME = "index.json";

export const BLOG_RAW_BASE = `https://raw.githubusercontent.com/${BLOG_REPO_OWNER}/${BLOG_REPO_NAME}/${BLOG_REPO_BRANCH}/${BLOG_CONTENT_DIR}`;

export function blogRawIndexUrl(base: string = BLOG_RAW_BASE): string {
  return `${base}/${BLOG_INDEX_FILENAME}`;
}

export function blogRawPostUrl(slug: string, base: string = BLOG_RAW_BASE): string {
  return `${base}/${slug}.md`;
}
